//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from EasyHue.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="EasyHueParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.CLSCompliant(false)]
public interface IEasyHueListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyHueParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] EasyHueParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyHueParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] EasyHueParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyHueParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] EasyHueParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyHueParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] EasyHueParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyHueParser.functionDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDefinition([NotNull] EasyHueParser.FunctionDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyHueParser.functionDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDefinition([NotNull] EasyHueParser.FunctionDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyHueParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] EasyHueParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyHueParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] EasyHueParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyHueParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCall([NotNull] EasyHueParser.FunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyHueParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCall([NotNull] EasyHueParser.FunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyHueParser.keywordCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeywordCall([NotNull] EasyHueParser.KeywordCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyHueParser.keywordCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeywordCall([NotNull] EasyHueParser.KeywordCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyHueParser.keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyword([NotNull] EasyHueParser.KeywordContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyHueParser.keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyword([NotNull] EasyHueParser.KeywordContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyHueParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameters([NotNull] EasyHueParser.ParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyHueParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameters([NotNull] EasyHueParser.ParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyHueParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArguments([NotNull] EasyHueParser.ArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyHueParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArguments([NotNull] EasyHueParser.ArgumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyHueParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] EasyHueParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyHueParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] EasyHueParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyHueParser.binaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinaryOperator([NotNull] EasyHueParser.BinaryOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyHueParser.binaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinaryOperator([NotNull] EasyHueParser.BinaryOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyHueParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] EasyHueParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyHueParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] EasyHueParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyHueParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStatement([NotNull] EasyHueParser.WhileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyHueParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStatement([NotNull] EasyHueParser.WhileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyHueParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] EasyHueParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyHueParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] EasyHueParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyHueParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStatement([NotNull] EasyHueParser.ReturnStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyHueParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStatement([NotNull] EasyHueParser.ReturnStatementContext context);
}
