//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from EasyHue.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IEasyHueListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class EasyHueBaseListener : IEasyHueListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyHueParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] EasyHueParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyHueParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] EasyHueParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyHueParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] EasyHueParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyHueParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] EasyHueParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyHueParser.functionDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDefinition([NotNull] EasyHueParser.FunctionDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyHueParser.functionDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDefinition([NotNull] EasyHueParser.FunctionDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyHueParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] EasyHueParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyHueParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] EasyHueParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyHueParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionCall([NotNull] EasyHueParser.FunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyHueParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionCall([NotNull] EasyHueParser.FunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyHueParser.keywordCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeywordCall([NotNull] EasyHueParser.KeywordCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyHueParser.keywordCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeywordCall([NotNull] EasyHueParser.KeywordCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyHueParser.keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeyword([NotNull] EasyHueParser.KeywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyHueParser.keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeyword([NotNull] EasyHueParser.KeywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyHueParser.parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameters([NotNull] EasyHueParser.ParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyHueParser.parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameters([NotNull] EasyHueParser.ParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyHueParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArguments([NotNull] EasyHueParser.ArgumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyHueParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArguments([NotNull] EasyHueParser.ArgumentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyHueParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] EasyHueParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyHueParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] EasyHueParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyHueParser.binaryOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinaryOperator([NotNull] EasyHueParser.BinaryOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyHueParser.binaryOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinaryOperator([NotNull] EasyHueParser.BinaryOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyHueParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] EasyHueParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyHueParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] EasyHueParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyHueParser.whileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileStatement([NotNull] EasyHueParser.WhileStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyHueParser.whileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileStatement([NotNull] EasyHueParser.WhileStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyHueParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] EasyHueParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyHueParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] EasyHueParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyHueParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStatement([NotNull] EasyHueParser.ReturnStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyHueParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStatement([NotNull] EasyHueParser.ReturnStatementContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
